LR8/lab08/catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:processor_id>/', views.detail, name='detail'),
]

LR8/lab08/lab08/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

LR8/lab08/catalog/models.py
from django.db import models


class Processor(models.Model):
    name = models.CharField(max_length=20)


class Description(models.Model):
    processor_id = models.ForeignKey(Processor, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)

LR8/lab08/catalog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader

from .models import Processor
from .models import Description


def index(request):
    processors_list = Processor.objects.all()
    context = {'processors_list': processors_list}
    return render(request, 'catalog/index.html', context)


def detail(request, processor_id):
    processors_list = Processor.objects.all()
    for i in processors_list:
        if i.id == processor_id:
            processor = i
    description = get_object_or_404(Description, pk=processor_id)
    return render(request, 'catalog/detail.html', {'processor': processor, 'description': description})

LR8/lab08/catalog/templates/catalog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid modal-header">
            <a class="navbar-brand" href="/catalog/">Каталог</a>
        </div>
    </nav>
    <main class="container-fluid bg-dark">
        <div class="row justify-content-center">
            <div class="col-4">
                <h1 class="text-center text-light">{{ processor.name }}</h1>
                <table class="table table-dark table-borderless">
                    <tr>
                        <td class="text-light td-text-short">{{ description.description }}</td>
                        <td>
                            {% if processor.id == 1 %}
                            <img src="{% static "catalog/images/i3.png" %}" alt="image of i3" class="rounded img-fluid">
                            {% endif %}
                            {% if processor.id == 2 %}
                            <img src="{% static "catalog/images/i5.png" %}" alt="image of i3" class="rounded img-fluid">
                            {% endif %}
                            {% if processor.id == 3 %}
                            <img src="{% static "catalog/images/i7.png" %}" alt="image of i3" class="rounded img-fluid">
                            {% endif %}
                            {% if processor.id == 4 %}
                            <img src="{% static "catalog/images/i9.png" %}" alt="image of i3" class="rounded img-fluid">
                            {% endif %}
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </main>
    <footer class="high bg-dark">
    </footer>
</body>
</html>

LR8/lab08/catalog/templates/catalog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Catalog</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'catalog/style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid modal-header">
            <a class="navbar-brand" href="/catalog/">Каталог</a>
        </div>
    </nav>
    <main class="container-fluid bg-dark">
        <div class="row justify-content-left">
            <div class="col-4">
                {% if processors_list %}
                    <ul type="nav">
                    {% for processor in processors_list %}
                        <li class="nav-item">
                            <a class="nav-link list" href="{% url 'catalog:detail' processor.id %}">{{ processor.name }}</a>
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <p>No processors are available.</p>
                {% endif %}
            </div>
        </div>
    </main>
    <footer class="high bg-dark">
    </footer>
</body>
</html>